name: Delivery

on:
  push:
    branches: ['production']
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'production'
    steps:
      - name: Deploy
        run: echo 'Deploy app'
